version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.7.0
    ports:
      - 9200:9200
      - 9300:9300
    privileged: true
    environment:
      - xpack.security.enabled=false

  kibana:
    image: kibana:6.7.0
    ports:
      - 5601:5601
    privileged: true
